# Generated by Django 5.2.17 on 2026-10-01 00:32

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('password', models.CharField(db_column='senha', max_length=128, verbose_name='senha')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acesso ao painel admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
    ]
